import { MigrationInterface, QueryRunner } from "typeorm";

export class G2JobCompanyEntities1787133494290 implements MigrationInterface {
    name = 'G2JobCompanyEntities1787133494290'

    public async up(queryRunner: QueryRunner): Promise<void> {
        await queryRunner.query(`ALTER TABLE "resumes" DROP CONSTRAINT "FK_resumes_candidate_id"`);
        await queryRunner.query(`ALTER TABLE "candidate_skills" DROP CONSTRAINT "FK_candidate_skills_candidate_id"`);
        await queryRunner.query(`ALTER TABLE "candidate_skills" DROP CONSTRAINT "FK_candidate_skills_skill_id"`);
        await queryRunner.query(`ALTER TABLE "educations" DROP CONSTRAINT "FK_educations_candidate_id"`);
        await queryRunner.query(`ALTER TABLE "applications" DROP CONSTRAINT "FK_applications_candidate_id"`);
        await queryRunner.query(`ALTER TABLE "applications" DROP CONSTRAINT "FK_applications_resume_candidate"`);
        await queryRunner.query(`ALTER TABLE "certificates" DROP CONSTRAINT "FK_certificates_candidate_id"`);
        await queryRunner.query(`ALTER TABLE "candidate_languages" DROP CONSTRAINT "FK_candidate_languages_candidate_id"`);
        await queryRunner.query(`ALTER TABLE "candidate_languages" DROP CONSTRAINT "FK_candidate_languages_language_id"`);
        await queryRunner.query(`ALTER TABLE "work_experiences" DROP CONSTRAINT "FK_work_experiences_candidate_id"`);
        await queryRunner.query(`ALTER TABLE "role_permissions" DROP CONSTRAINT "fk_role_permissions_permission"`);
        await queryRunner.query(`ALTER TABLE "role_permissions" DROP CONSTRAINT "fk_role_permissions_role"`);
        await queryRunner.query(`ALTER TABLE "sessions" DROP CONSTRAINT "fk_sessions_user"`);
        await queryRunner.query(`ALTER TABLE "user_oauth_accounts" DROP CONSTRAINT "fk_user_oauth_accounts_user"`);
        await queryRunner.query(`ALTER TABLE "users" DROP CONSTRAINT "fk_users_role"`);
        await queryRunner.query(`ALTER TABLE "users" DROP CONSTRAINT "fk_users_ward"`);
        await queryRunner.query(`ALTER TABLE "saved_jobs" DROP CONSTRAINT "FK_saved_jobs_candidate_id"`);
        await queryRunner.query(`DROP INDEX "public"."uq_resumes_default_active"`);
        await queryRunner.query(`DROP INDEX "public"."idx_resumes_candidate_id"`);
        await queryRunner.query(`DROP INDEX "public"."idx_candidate_skills_skill_id"`);
        await queryRunner.query(`DROP INDEX "public"."idx_educations_candidate_id"`);
        await queryRunner.query(`DROP INDEX "public"."idx_applications_candidate_applied_at"`);
        await queryRunner.query(`DROP INDEX "public"."idx_applications_job_status"`);
        await queryRunner.query(`DROP INDEX "public"."idx_certificates_candidate_id"`);
        await queryRunner.query(`DROP INDEX "public"."uq_languages_code"`);
        await queryRunner.query(`DROP INDEX "public"."idx_candidate_languages_language_id"`);
        await queryRunner.query(`DROP INDEX "public"."idx_work_experiences_candidate_id"`);
        await queryRunner.query(`DROP INDEX "public"."idx_saved_jobs_candidate_created_at"`);
        await queryRunner.query(`DROP INDEX "public"."idx_saved_jobs_job_id"`);
        await queryRunner.query(`ALTER TABLE "resumes" DROP CONSTRAINT "CHK_resumes_file_size"`);
        await queryRunner.query(`ALTER TABLE "skills" DROP CONSTRAINT "CHK_skills_status"`);
        await queryRunner.query(`ALTER TABLE "educations" DROP CONSTRAINT "CHK_educations_dates"`);
        await queryRunner.query(`ALTER TABLE "educations" DROP CONSTRAINT "CHK_educations_current"`);
        await queryRunner.query(`ALTER TABLE "certificates" DROP CONSTRAINT "CHK_certificates_dates"`);
        await queryRunner.query(`ALTER TABLE "languages" DROP CONSTRAINT "CHK_languages_status"`);
        await queryRunner.query(`ALTER TABLE "work_experiences" DROP CONSTRAINT "CHK_work_exp_dates"`);
        await queryRunner.query(`ALTER TABLE "work_experiences" DROP CONSTRAINT "CHK_work_exp_current"`);
        await queryRunner.query(`ALTER TABLE "resumes" DROP CONSTRAINT "UQ_resumes_id_candidate"`);
        await queryRunner.query(`ALTER TABLE "candidate_skills" DROP CONSTRAINT "UQ_candidate_skills_candidate_skill"`);
        await queryRunner.query(`ALTER TABLE "applications" DROP CONSTRAINT "UQ_applications_candidate_job"`);
        await queryRunner.query(`ALTER TABLE "candidate_languages" DROP CONSTRAINT "UQ_candidate_languages_candidate_language"`);
        await queryRunner.query(`ALTER TABLE "role_permissions" DROP CONSTRAINT "uq_role_permissions"`);
        await queryRunner.query(`ALTER TABLE "user_oauth_accounts" DROP CONSTRAINT "uq_oauth_provider_account"`);
        await queryRunner.query(`ALTER TABLE "user_oauth_accounts" DROP CONSTRAINT "uq_user_oauth_provider"`);
        await queryRunner.query(`ALTER TABLE "saved_jobs" DROP CONSTRAINT "UQ_saved_jobs_candidate_job"`);
        await queryRunner.query(`CREATE TABLE "companies" ("id" BIGSERIAL NOT NULL, "user_id" bigint NOT NULL, "name" character varying(255) NOT NULL, "slug" character varying(255) NOT NULL, "logo" character varying(255), "website" character varying(255), "email" character varying(255) NOT NULL, "phone" character varying(20) NOT NULL, "tax_code" character varying(50), "company_size" character varying(50), "address" character varying(255) NOT NULL, "description" text, "status" character varying(30) NOT NULL DEFAULT 'ACTIVE', "created_at" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now(), "updated_at" TIMESTAMP WITH TIME ZONE DEFAULT now(), "deleted_at" TIMESTAMP WITH TIME ZONE, CONSTRAINT "UQ_ee0839cba07cb0c52602021ad4b" UNIQUE ("user_id"), CONSTRAINT "UQ_b28b07d25e4324eee577de5496d" UNIQUE ("slug"), CONSTRAINT "PK_d4bc3e82a314fa9e29f652c2c22" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE TABLE "job_categories" ("id" BIGSERIAL NOT NULL, "name" character varying(150) NOT NULL, "slug" character varying(150) NOT NULL, "description" text, "status" character varying(30) NOT NULL DEFAULT 'ACTIVE', "created_at" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now(), "updated_at" TIMESTAMP WITH TIME ZONE DEFAULT now(), "deleted_at" TIMESTAMP WITH TIME ZONE, CONSTRAINT "UQ_2e5f6c46d136907967008b9bb68" UNIQUE ("name"), CONSTRAINT "UQ_c093b33c90d9fe79f7419209eaa" UNIQUE ("slug"), CONSTRAINT "PK_a3558e7de1e1252863bc01af86f" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE TABLE "job_skills" ("id" BIGSERIAL NOT NULL, "job_id" bigint NOT NULL, "skill_id" bigint NOT NULL, "is_required" boolean NOT NULL DEFAULT true, CONSTRAINT "PK_79dc7f5be80bfe7a4e590a71041" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE UNIQUE INDEX "idx_job_skills_job_skill_unique" ON "job_skills" ("job_id", "skill_id") `);
        await queryRunner.query(`CREATE TABLE "jobs" ("id" BIGSERIAL NOT NULL, "company_id" bigint NOT NULL, "category_id" bigint NOT NULL, "title" character varying(255) NOT NULL, "slug" character varying(255) NOT NULL, "description" text NOT NULL, "requirements" text NOT NULL, "benefits" text, "salary_min" numeric(15,2), "salary_max" numeric(15,2), "is_negotiable" boolean NOT NULL DEFAULT false, "address" character varying(255) NOT NULL, "job_type" character varying(50) NOT NULL DEFAULT 'FULL_TIME', "job_mode" character varying(50) NOT NULL DEFAULT 'ONSITE', "experience" integer, "quantity" integer DEFAULT '1', "deadline" date NOT NULL, "reject_reason" text, "status" character varying(30) NOT NULL DEFAULT 'PENDING', "created_at" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now(), "updated_at" TIMESTAMP WITH TIME ZONE DEFAULT now(), "deleted_at" TIMESTAMP WITH TIME ZONE, CONSTRAINT "PK_cf0a6c42b72fcc7f7c237def345" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE INDEX "idx_jobs_status" ON "jobs" ("status") `);
        await queryRunner.query(`CREATE INDEX "idx_jobs_category_id" ON "jobs" ("category_id") `);
        await queryRunner.query(`CREATE INDEX "idx_jobs_company_id" ON "jobs" ("company_id") `);
        await queryRunner.query(`ALTER TABLE "skills" ADD CONSTRAINT "UQ_81f05095507fd84aa2769b4a522" UNIQUE ("name")`);
        await queryRunner.query(`ALTER TABLE "applications" ALTER COLUMN "applied_at" SET DEFAULT now()`);
        await queryRunner.query(`CREATE UNIQUE INDEX "uq_role_permissions" ON "role_permissions" ("role_id", "permission_id") `);
        await queryRunner.query(`CREATE UNIQUE INDEX "uq_user_oauth_provider" ON "user_oauth_accounts" ("user_id", "provider") `);
        await queryRunner.query(`CREATE UNIQUE INDEX "uq_oauth_provider_account" ON "user_oauth_accounts" ("provider", "provider_user_id") `);
        await queryRunner.query(`ALTER TABLE "resumes" ADD CONSTRAINT "UQ_e15dd2fe54a4ffaac63b0f73054" UNIQUE ("id", "candidate_id")`);
        await queryRunner.query(`ALTER TABLE "candidate_skills" ADD CONSTRAINT "UQ_7a47825b1d04e8710c83f1a1043" UNIQUE ("candidate_id", "skill_id")`);
        await queryRunner.query(`ALTER TABLE "applications" ADD CONSTRAINT "UQ_d1a0f9040afc46f7672793a391a" UNIQUE ("candidate_id", "job_id")`);
        await queryRunner.query(`ALTER TABLE "candidate_languages" ADD CONSTRAINT "UQ_66ac3974bd1d8fd23e1d4ff6671" UNIQUE ("candidate_id", "language_id")`);
        await queryRunner.query(`ALTER TABLE "saved_jobs" ADD CONSTRAINT "UQ_55829e64a48f4b836a55ba3bf0c" UNIQUE ("candidate_id", "job_id")`);
        await queryRunner.query(`ALTER TABLE "resumes" ADD CONSTRAINT "FK_12798a26b559b6468747b233847" FOREIGN KEY ("candidate_id") REFERENCES "candidate_profiles"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "candidate_skills" ADD CONSTRAINT "FK_bb3474452a29e2537ebd0ea22f8" FOREIGN KEY ("candidate_id") REFERENCES "candidate_profiles"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "candidate_skills" ADD CONSTRAINT "FK_c84d2943849a7f0f8bec796572d" FOREIGN KEY ("skill_id") REFERENCES "skills"("id") ON DELETE RESTRICT ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "educations" ADD CONSTRAINT "FK_7be3038b94f0416ead817dfcd47" FOREIGN KEY ("candidate_id") REFERENCES "candidate_profiles"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "applications" ADD CONSTRAINT "FK_b669b991b85b808f24b5734990a" FOREIGN KEY ("candidate_id") REFERENCES "candidate_profiles"("id") ON DELETE RESTRICT ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "applications" ADD CONSTRAINT "FK_241f549e92b54bb3538c9bdcf21" FOREIGN KEY ("resume_id") REFERENCES "resumes"("id") ON DELETE RESTRICT ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "certificates" ADD CONSTRAINT "FK_f0be5d1b8b27ea1178fbe78848b" FOREIGN KEY ("candidate_id") REFERENCES "candidate_profiles"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "candidate_languages" ADD CONSTRAINT "FK_dbcdd48e60c72f143c42694d7a0" FOREIGN KEY ("candidate_id") REFERENCES "candidate_profiles"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "candidate_languages" ADD CONSTRAINT "FK_e36d97db1e100f22b7daf0fbc1d" FOREIGN KEY ("language_id") REFERENCES "languages"("id") ON DELETE RESTRICT ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "work_experiences" ADD CONSTRAINT "FK_209384ea01bce5b6256fa544ff2" FOREIGN KEY ("candidate_id") REFERENCES "candidate_profiles"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "role_permissions" ADD CONSTRAINT "FK_178199805b901ccd220ab7740ec" FOREIGN KEY ("role_id") REFERENCES "roles"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "role_permissions" ADD CONSTRAINT "FK_17022daf3f885f7d35423e9971e" FOREIGN KEY ("permission_id") REFERENCES "permissions"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "sessions" ADD CONSTRAINT "FK_085d540d9f418cfbdc7bd55bb19" FOREIGN KEY ("user_id") REFERENCES "users"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "user_oauth_accounts" ADD CONSTRAINT "FK_a093a39110ecd3602d87f0e814b" FOREIGN KEY ("user_id") REFERENCES "users"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "users" ADD CONSTRAINT "FK_a2cecd1a3531c0b041e29ba46e1" FOREIGN KEY ("role_id") REFERENCES "roles"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "saved_jobs" ADD CONSTRAINT "FK_a3550195e29799042b9c8313c83" FOREIGN KEY ("candidate_id") REFERENCES "candidate_profiles"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "companies" ADD CONSTRAINT "FK_ee0839cba07cb0c52602021ad4b" FOREIGN KEY ("user_id") REFERENCES "users"("id") ON DELETE RESTRICT ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "job_skills" ADD CONSTRAINT "FK_4f7427e13d249156f37669e7127" FOREIGN KEY ("job_id") REFERENCES "jobs"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "job_skills" ADD CONSTRAINT "FK_7c0a3c52e77f9d9d839fdbb14b6" FOREIGN KEY ("skill_id") REFERENCES "skills"("id") ON DELETE RESTRICT ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "jobs" ADD CONSTRAINT "FK_087a773c50525e348e26188e7cc" FOREIGN KEY ("company_id") REFERENCES "companies"("id") ON DELETE RESTRICT ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "jobs" ADD CONSTRAINT "FK_652419b4e4717ce9c426832c211" FOREIGN KEY ("category_id") REFERENCES "job_categories"("id") ON DELETE RESTRICT ON UPDATE NO ACTION`);
    }

    public async down(queryRunner: QueryRunner): Promise<void> {
        await queryRunner.query(`ALTER TABLE "jobs" DROP CONSTRAINT "FK_652419b4e4717ce9c426832c211"`);
        await queryRunner.query(`ALTER TABLE "jobs" DROP CONSTRAINT "FK_087a773c50525e348e26188e7cc"`);
        await queryRunner.query(`ALTER TABLE "job_skills" DROP CONSTRAINT "FK_7c0a3c52e77f9d9d839fdbb14b6"`);
        await queryRunner.query(`ALTER TABLE "job_skills" DROP CONSTRAINT "FK_4f7427e13d249156f37669e7127"`);
        await queryRunner.query(`ALTER TABLE "companies" DROP CONSTRAINT "FK_ee0839cba07cb0c52602021ad4b"`);
        await queryRunner.query(`ALTER TABLE "saved_jobs" DROP CONSTRAINT "FK_a3550195e29799042b9c8313c83"`);
        await queryRunner.query(`ALTER TABLE "users" DROP CONSTRAINT "FK_a2cecd1a3531c0b041e29ba46e1"`);
        await queryRunner.query(`ALTER TABLE "user_oauth_accounts" DROP CONSTRAINT "FK_a093a39110ecd3602d87f0e814b"`);
        await queryRunner.query(`ALTER TABLE "sessions" DROP CONSTRAINT "FK_085d540d9f418cfbdc7bd55bb19"`);
        await queryRunner.query(`ALTER TABLE "role_permissions" DROP CONSTRAINT "FK_17022daf3f885f7d35423e9971e"`);
        await queryRunner.query(`ALTER TABLE "role_permissions" DROP CONSTRAINT "FK_178199805b901ccd220ab7740ec"`);
        await queryRunner.query(`ALTER TABLE "work_experiences" DROP CONSTRAINT "FK_209384ea01bce5b6256fa544ff2"`);
        await queryRunner.query(`ALTER TABLE "candidate_languages" DROP CONSTRAINT "FK_e36d97db1e100f22b7daf0fbc1d"`);
        await queryRunner.query(`ALTER TABLE "candidate_languages" DROP CONSTRAINT "FK_dbcdd48e60c72f143c42694d7a0"`);
        await queryRunner.query(`ALTER TABLE "certificates" DROP CONSTRAINT "FK_f0be5d1b8b27ea1178fbe78848b"`);
        await queryRunner.query(`ALTER TABLE "applications" DROP CONSTRAINT "FK_241f549e92b54bb3538c9bdcf21"`);
        await queryRunner.query(`ALTER TABLE "applications" DROP CONSTRAINT "FK_b669b991b85b808f24b5734990a"`);
        await queryRunner.query(`ALTER TABLE "educations" DROP CONSTRAINT "FK_7be3038b94f0416ead817dfcd47"`);
        await queryRunner.query(`ALTER TABLE "candidate_skills" DROP CONSTRAINT "FK_c84d2943849a7f0f8bec796572d"`);
        await queryRunner.query(`ALTER TABLE "candidate_skills" DROP CONSTRAINT "FK_bb3474452a29e2537ebd0ea22f8"`);
        await queryRunner.query(`ALTER TABLE "resumes" DROP CONSTRAINT "FK_12798a26b559b6468747b233847"`);
        await queryRunner.query(`ALTER TABLE "saved_jobs" DROP CONSTRAINT "UQ_55829e64a48f4b836a55ba3bf0c"`);
        await queryRunner.query(`ALTER TABLE "candidate_languages" DROP CONSTRAINT "UQ_66ac3974bd1d8fd23e1d4ff6671"`);
        await queryRunner.query(`ALTER TABLE "applications" DROP CONSTRAINT "UQ_d1a0f9040afc46f7672793a391a"`);
        await queryRunner.query(`ALTER TABLE "candidate_skills" DROP CONSTRAINT "UQ_7a47825b1d04e8710c83f1a1043"`);
        await queryRunner.query(`ALTER TABLE "resumes" DROP CONSTRAINT "UQ_e15dd2fe54a4ffaac63b0f73054"`);
        await queryRunner.query(`DROP INDEX "public"."uq_oauth_provider_account"`);
        await queryRunner.query(`DROP INDEX "public"."uq_user_oauth_provider"`);
        await queryRunner.query(`DROP INDEX "public"."uq_role_permissions"`);
        await queryRunner.query(`ALTER TABLE "applications" ALTER COLUMN "applied_at" SET DEFAULT CURRENT_TIMESTAMP`);
        await queryRunner.query(`ALTER TABLE "skills" DROP CONSTRAINT "UQ_81f05095507fd84aa2769b4a522"`);
        await queryRunner.query(`DROP INDEX "public"."idx_jobs_company_id"`);
        await queryRunner.query(`DROP INDEX "public"."idx_jobs_category_id"`);
        await queryRunner.query(`DROP INDEX "public"."idx_jobs_status"`);
        await queryRunner.query(`DROP TABLE "jobs"`);
        await queryRunner.query(`DROP INDEX "public"."idx_job_skills_job_skill_unique"`);
        await queryRunner.query(`DROP TABLE "job_skills"`);
        await queryRunner.query(`DROP TABLE "job_categories"`);
        await queryRunner.query(`DROP TABLE "companies"`);
        await queryRunner.query(`ALTER TABLE "saved_jobs" ADD CONSTRAINT "UQ_saved_jobs_candidate_job" UNIQUE ("candidate_id", "job_id")`);
        await queryRunner.query(`ALTER TABLE "user_oauth_accounts" ADD CONSTRAINT "uq_user_oauth_provider" UNIQUE ("user_id", "provider")`);
        await queryRunner.query(`ALTER TABLE "user_oauth_accounts" ADD CONSTRAINT "uq_oauth_provider_account" UNIQUE ("provider", "provider_user_id")`);
        await queryRunner.query(`ALTER TABLE "role_permissions" ADD CONSTRAINT "uq_role_permissions" UNIQUE ("role_id", "permission_id")`);
        await queryRunner.query(`ALTER TABLE "candidate_languages" ADD CONSTRAINT "UQ_candidate_languages_candidate_language" UNIQUE ("candidate_id", "language_id")`);
        await queryRunner.query(`ALTER TABLE "applications" ADD CONSTRAINT "UQ_applications_candidate_job" UNIQUE ("candidate_id", "job_id")`);
        await queryRunner.query(`ALTER TABLE "candidate_skills" ADD CONSTRAINT "UQ_candidate_skills_candidate_skill" UNIQUE ("candidate_id", "skill_id")`);
        await queryRunner.query(`ALTER TABLE "resumes" ADD CONSTRAINT "UQ_resumes_id_candidate" UNIQUE ("id", "candidate_id")`);
        await queryRunner.query(`ALTER TABLE "work_experiences" ADD CONSTRAINT "CHK_work_exp_current" CHECK (((is_current = false) OR (end_date IS NULL)))`);
        await queryRunner.query(`ALTER TABLE "work_experiences" ADD CONSTRAINT "CHK_work_exp_dates" CHECK (((end_date IS NULL) OR (end_date >= start_date)))`);
        await queryRunner.query(`ALTER TABLE "languages" ADD CONSTRAINT "CHK_languages_status" CHECK (((status)::text = ANY ((ARRAY['ACTIVE'::character varying, 'INACTIVE'::character varying])::text[])))`);
        await queryRunner.query(`ALTER TABLE "certificates" ADD CONSTRAINT "CHK_certificates_dates" CHECK (((expiry_date IS NULL) OR (issue_date IS NULL) OR (expiry_date >= issue_date)))`);
        await queryRunner.query(`ALTER TABLE "educations" ADD CONSTRAINT "CHK_educations_current" CHECK (((is_current = false) OR (end_date IS NULL)))`);
        await queryRunner.query(`ALTER TABLE "educations" ADD CONSTRAINT "CHK_educations_dates" CHECK (((end_date IS NULL) OR (end_date >= start_date)))`);
        await queryRunner.query(`ALTER TABLE "skills" ADD CONSTRAINT "CHK_skills_status" CHECK (((status)::text = ANY ((ARRAY['ACTIVE'::character varying, 'INACTIVE'::character varying])::text[])))`);
        await queryRunner.query(`ALTER TABLE "resumes" ADD CONSTRAINT "CHK_resumes_file_size" CHECK ((file_size > 0))`);
        await queryRunner.query(`CREATE INDEX "idx_saved_jobs_job_id" ON "saved_jobs" ("job_id") `);
        await queryRunner.query(`CREATE INDEX "idx_saved_jobs_candidate_created_at" ON "saved_jobs" ("candidate_id", "created_at") `);
        await queryRunner.query(`CREATE INDEX "idx_work_experiences_candidate_id" ON "work_experiences" ("candidate_id") `);
        await queryRunner.query(`CREATE INDEX "idx_candidate_languages_language_id" ON "candidate_languages" ("language_id") `);
        await queryRunner.query(`CREATE UNIQUE INDEX "uq_languages_code" ON "languages" ("code") WHERE (code IS NOT NULL)`);
        await queryRunner.query(`CREATE INDEX "idx_certificates_candidate_id" ON "certificates" ("candidate_id") `);
        await queryRunner.query(`CREATE INDEX "idx_applications_job_status" ON "applications" ("job_id", "status") `);
        await queryRunner.query(`CREATE INDEX "idx_applications_candidate_applied_at" ON "applications" ("applied_at", "candidate_id") `);
        await queryRunner.query(`CREATE INDEX "idx_educations_candidate_id" ON "educations" ("candidate_id") `);
        await queryRunner.query(`CREATE INDEX "idx_candidate_skills_skill_id" ON "candidate_skills" ("skill_id") `);
        await queryRunner.query(`CREATE INDEX "idx_resumes_candidate_id" ON "resumes" ("candidate_id") `);
        await queryRunner.query(`CREATE UNIQUE INDEX "uq_resumes_default_active" ON "resumes" ("candidate_id") WHERE ((is_default = true) AND (deleted_at IS NULL))`);
        await queryRunner.query(`ALTER TABLE "saved_jobs" ADD CONSTRAINT "FK_saved_jobs_candidate_id" FOREIGN KEY ("candidate_id") REFERENCES "candidate_profiles"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "users" ADD CONSTRAINT "fk_users_ward" FOREIGN KEY ("ward_code") REFERENCES "wards"("code") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "users" ADD CONSTRAINT "fk_users_role" FOREIGN KEY ("role_id") REFERENCES "roles"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "user_oauth_accounts" ADD CONSTRAINT "fk_user_oauth_accounts_user" FOREIGN KEY ("user_id") REFERENCES "users"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "sessions" ADD CONSTRAINT "fk_sessions_user" FOREIGN KEY ("user_id") REFERENCES "users"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "role_permissions" ADD CONSTRAINT "fk_role_permissions_role" FOREIGN KEY ("role_id") REFERENCES "roles"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "role_permissions" ADD CONSTRAINT "fk_role_permissions_permission" FOREIGN KEY ("permission_id") REFERENCES "permissions"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "work_experiences" ADD CONSTRAINT "FK_work_experiences_candidate_id" FOREIGN KEY ("candidate_id") REFERENCES "candidate_profiles"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "candidate_languages" ADD CONSTRAINT "FK_candidate_languages_language_id" FOREIGN KEY ("language_id") REFERENCES "languages"("id") ON DELETE RESTRICT ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "candidate_languages" ADD CONSTRAINT "FK_candidate_languages_candidate_id" FOREIGN KEY ("candidate_id") REFERENCES "candidate_profiles"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "certificates" ADD CONSTRAINT "FK_certificates_candidate_id" FOREIGN KEY ("candidate_id") REFERENCES "candidate_profiles"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "applications" ADD CONSTRAINT "FK_applications_resume_candidate" FOREIGN KEY ("resume_id", "candidate_id") REFERENCES "resumes"("id","candidate_id") ON DELETE RESTRICT ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "applications" ADD CONSTRAINT "FK_applications_candidate_id" FOREIGN KEY ("candidate_id") REFERENCES "candidate_profiles"("id") ON DELETE RESTRICT ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "educations" ADD CONSTRAINT "FK_educations_candidate_id" FOREIGN KEY ("candidate_id") REFERENCES "candidate_profiles"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "candidate_skills" ADD CONSTRAINT "FK_candidate_skills_skill_id" FOREIGN KEY ("skill_id") REFERENCES "skills"("id") ON DELETE RESTRICT ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "candidate_skills" ADD CONSTRAINT "FK_candidate_skills_candidate_id" FOREIGN KEY ("candidate_id") REFERENCES "candidate_profiles"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "resumes" ADD CONSTRAINT "FK_resumes_candidate_id" FOREIGN KEY ("candidate_id") REFERENCES "candidate_profiles"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
    }

}
